### PR TITLE
Making our conf management a tad more sane

### PR DESCRIPTION
**Pull request by rvs**

### CODE REVIEW

**Comment by rvs** [comment]
I didn't see it mentioned anywhere in the source of go-provision (did git grep for it use). And I believe we had a conversation to remove it. But can you please also verify that on go-provision end?

**Comment by eriknordmark** [comment]
The issue is the code in init.sh in zenbuild which uses cert-input.
Did you test that the onboarding works without this file?

**Comment by rvs** [comment]
Yes that's what I meant -- it seems to work. At the same time I couldn't explain why -- hence my question to you ;-)

**Comment by rvs** [comment]
And it has just occurred to me that the change to init.sh is indeed still sitting in my repo instead of being part of this pull request. Well spotted! And a reminder that a PR for zenbuild should NEVER come when there's a -dirty tag on any of the resulting containers :-(

**Comment by rvs** [comment]
Pushed and close!

**Pull request closed without merging**
