### PR TITLE
Importing linuxkit and manifest-tool to make us self-contained

### PR DESCRIPTION
**Pull request by rvs**
This is pretty self-explanatory. Please review!

### CODE REVIEW

**Comment by gianlzed** [comment]
This is the worst possible way to go. We want to use linuxkit repo? Then we need to import our zenbuild into our own fork of linuxkit, and gradually merging the two -- the latter is already happening.

LinuxKit is way bigger than us, and there are two ways.

Either we use the output, as we do now, and use it as a toolchain, but then we need to use git submodule or repo or even a separate repository. Actually, the latter is what zdk *is*.

Or we make zenbuild an extension of linuxkit. This was my first attempt and the way I originally build this.

This is a mid way which makes everything more complicated, including updating linuxkit, or tracking its changes.

**Comment by rvs** [comment]
@gianlzed @glguida it would be nice if didn't close issue, until we actually get some consensus. Sounds good? I'm taking a liberty of reopening it.

2nd of all, what is the real problem with this approach? This is no different from Go project vendoring in their dependencies -- linuxkit is undergoing very rapid development and we simply can't expect all our consumers having the version that is guaranteed to produce the correct result for us. Hence we have to have a way to peg the exact SHA of linuxkit.

The only alternative way I see how this could be done is to git checkout that every time you don't have the linuxkit available. This is an inferior solution in my view, sine we don't actually need ALL of linuxkit -- we just need a Go dependecy. Thus git cloning 90% of stuff you don't need seems pretty silly.

Does this make things clearer?

**Comment by gianlzed** [comment]
@rvs, git submodule. Don't love it but it's the best thing in this case. Especially because our plan is to gradually merge our changes into them. We could point it to our local fork of linux kit, and this will be much better than this for two reasons:

1) will be more clear in knowing what version of linuxkit we're actually using.
2) It'll be easier to know which patch we're applying to linuxkit, for future merging.

Re consensus,

**Comment by rvs** [comment]
OK, I finally managed to redo this PR using the proper Go tools. Please take a look now. The importing magic happens in Gopkg.toml files. E.g.:
   https://github.com/rvs/zenbuild/blob/master/build-tools/src/linuxkit/Gopkg.toml
and
   https://github.com/rvs/zenbuild/blob/master/build-tools/src/manifest-tool/Gopkg.toml

**Comment by glguida** [comment]
Oh, very nice. I think we should say that we now require go. And that we are probably a go-project officially. ;)

LGTM!

**Comment by rvs** [comment]
I fixed a few small issues and also updated a README file as per @glguida suggestion. Merging soon now, unless there are any objections.

**Pull request merged**
