### PR TITLE
mkflash/make-raw needs to handle new dist

### PR DESCRIPTION
**Pull request by eriknordmark**
@deitch I don't see to be able to add you as a reviewer.

### CODE REVIEW

**Comment by deitch** [comment]
I’m not a writer or admin of this repo. Can you add me @eriknordmark or @rvs ?

**Comment by deitch** [comment]
And thank you for catching it.

**Comment by eriknordmark** [comment]
@deitch I just realized there is also a symlink issue with fallback.img -> dist/amd64/fallback.qcow2, but too late for me to fix that tonight.

**Comment by deitch** [comment]
> I just realized there is also a symlink issue with fallback.img -> dist/amd64/fallback.qcow2

I will get that right now.

**Comment by deitch** [comment]
Also, if you make me able to write or admin, I can do branches directly here.

**Comment by deitch** [comment]
See #82

**Comment by rvs** [comment]
@deitch we *really* don't want branched directly here

**Comment by rvs** [comment]
Hey @eriknordmark your change to mkimage-raw-efi broke the physical installer

I backed out your fix and testing a new one right now

**Comment by deitch** [comment]
I am happy to do on my own clone, it is fine. I suggested it because this PR is from `simplify` on local. I am happy either way.

**Pull request merged**
